INSERT INTO FUNCOES VALUES ('CADCUR', 'Cadastro de Cursos');
INSERT INTO FUNCOES VALUES ('CADINS', 'Cadastro de Instrutores');
INSERT INTO FUNCOES VALUES ('CADTUR', 'Cadastro de Turmas');
INSERT INTO FUNCOES VALUES ('CADALU', 'Cadastro de Alunos');
INSERT INTO FUNCOES VALUES ('CADMAT', 'Matrículas');
INSERT INTO FUNCOES VALUES ('ÇANAUL', 'Lançamento de Aulas');
INSERT INTO FUNCOES VALUES ('LANFRE', 'Frequncia');
INSERT INTO FUNCOES VALUES ('PAGINS', 'Pagamento de Instrutores');
INSERT INTO FUNCOES VALUES ('RELATO', 'Relatórios');
INSERT INTO FUNCOES VALUES ('CONTRO', 'Controle de Acesso');

/*SELECT*/
SELECT * FROM FUNCOES