INSERT INTO PERMISSOES VALUES ('CADCUR', 'administrador');
INSERT INTO PERMISSOES VALUES ('CADINS', 'administrador');
INSERT INTO PERMISSOES VALUES ('CADTUR', 'administrador');
INSERT INTO PERMISSOES VALUES ('CADALU', 'administrador');
INSERT INTO PERMISSOES VALUES ('CADMAT', 'administrador');
INSERT INTO PERMISSOES VALUES ('ÇANAUL', 'administrador');
INSERT INTO PERMISSOES VALUES ('LANFRE', 'administrador');
INSERT INTO PERMISSOES VALUES ('PAGINS', 'administrador');
INSERT INTO PERMISSOES VALUES ('RELATO', 'administrador');
INSERT INTO PERMISSOES VALUES ('CONTRO', 'administrador');

/*SELECT*/
SELECT * FROM PERMISSOES
